component: aws-iam-role@2.0.2
name: role
org: ${env:ORGANIZATION}
app: ouchi-worker
stage: dev

inputs:
  name: ${app}-${stage}
  policy:
    - Effect: Allow
      Action:
        - sts:AssumeRole
      Resource: '*'
    - Effect: Allow
      Action:
        - logs:CreateLogGroup
        - logs:CreateLogStream
        - logs:PutLogEvents
      Resource: '*'
    - Effect: Allow
      Action:
        - dynamodb:GetItem
        - dynamodb:PutItem
      Resource: ${output:cache.arn}
