# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-node@v2
      with:
        node-version: '12'
        check-latest: true
    
    - name: Build
      working-directory: check-human
      run: |
        yarn install
        yarn build

    - name: Serverless
      uses: serverless/github-action@v1.53.0
    
    - name: Deploy cache table
      working-directory: cache
    - run: serverless deploy

    - name: Deploy iam role
      working-directory: role
    - run: serverless deploy

    - name: Deploy function
      working-directory: check-human
    - run: serverless deploy
