# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2-beta
        with:
          node-version: "12"

      - name: Build
        working-directory: ./worker/check-human
        run: |
          yarn install
          yarn build

      - name: Deploy cache table
        uses: serverless/github-action@v1.53.0
        working-directory: ./worker/cache
        with:
          args: deploy
        env:
          SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          ORGANIZATION: ${{ secrets.ORGANIZATION }}
          NATURE_REMO_TOKEN: ${{ secrets.NATURE_REMO_TOKEN }}
          WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}

      - name: Deploy iam role
        uses: serverless/github-action@v1.53.0
        working-directory: ./worker/role
        with:
          args: deploy
        env:
          SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          ORGANIZATION: ${{ secrets.ORGANIZATION }}
          NATURE_REMO_TOKEN: ${{ secrets.NATURE_REMO_TOKEN }}
          WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}

      - name: Deploy function
        uses: serverless/github-action@v1.53.0
        working-directory: ./worker/check-human
        with:
          args: deploy
        env:
          SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          ORGANIZATION: ${{ secrets.ORGANIZATION }}
          NATURE_REMO_TOKEN: ${{ secrets.NATURE_REMO_TOKEN }}
          WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
